#!/usr/bin/env python3

from flask import Flask, request
import logging
import time

api = Flask(__name__)

@api.route('/', methods=['GET'])
def index():
    return 'Bem vindo a Gulliver Traveller!'

if __name__ == '__main__':
    api.run(debug=True, host='0.0.0.0', port=3000)
